[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "83e8542b2a27d969b4cf9f43c558684fe9c28b0c"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "d5355891c7114923b8df73e8072c13312506882986f04d0db249680399ae9b21"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.aarch64-linux-gnu.tar.gz"
[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "047d13a980199b45a134dbed48bbcfd6e580ba27"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "a1c212fb9078c236823bd79336abb28cda60b75f75e7d98146861e3813363b51"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.aarch64-linux-musl.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e156180c14a1fae9df64d949b112d597be67dac"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "02b8f1e14ecf59414deeff474421a59cd475397b86e026986553f8239de9dd56"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.armv7l-linux-gnueabihf.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8761ac83a194c497a1c83dde34428e4a5a72a5eb"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "2ab4c0810b5425b1a85aa79e9b0fc71e26189472ca12692b0735c73267907ad9"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.armv7l-linux-musleabihf.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "1ee9347b2366a4ca5e42e9be7e37e7fb47bee8ac"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "f6c4ea6d2e2e69d6db8602979b0ee6d4db9c73903eaa0d6666d6cf63bc1e963a"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.i686-linux-gnu.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "1a49ef441fb213e3abf05a348253a41fbcd846e7"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "8a7fce33f4256b700a370a74091596b0114791193e5a59ee3a8f36c0a1676a97"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.i686-linux-musl.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "d5b97f43eef013b9ddb76cd83557ecf60683713e"
os = "windows"

    [[ERFA.download]]
    sha256 = "dc11d20627ec9603a6491a34f514bfd22de01c7b8d0edbf8e23aaade974094d4"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.i686-w64-mingw32.tar.gz"
[[ERFA]]
arch = "powerpc64le"
git-tree-sha1 = "764a9436fd09ebbb19eb3c2ffd288b3bb628da24"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "2522eb2a54472be3edc704ae374acbb31d07e582cfb66d82e8a8105c03593b31"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.powerpc64le-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "efec8c0caa972227fec2b35d0a350b9b16f262ef"
os = "macos"

    [[ERFA.download]]
    sha256 = "289b0e3c9fe60fc30d8cbfeff3150ab3922ec81914560cc5c0cda81af4f37874"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.x86_64-apple-darwin.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "040eb1a475341e657bc2431af1d7f913adc55460"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "5aaf7d430dec6d224b4a26c6ccca6bbcdfd145f648c7fc2b384b0f89601491a6"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.x86_64-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "323163344b72713836e4c2fa1a33432a7f6eb4c6"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "7a5c23780c2d1e54df7ca0e6b561fa0c3fed22728fda5a56eafaebefa2f09e49"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.x86_64-linux-musl.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "ab269da516df79d271c37fa051e9fb505f34322b"
os = "freebsd"

    [[ERFA.download]]
    sha256 = "f3bfd56eda98261c679c68e7d8113c74ef906189ae4f14292871711034702a2b"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.x86_64-unknown-freebsd.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "8d6bdc3f9d03c36084d40d7df9d9f4f072bc40bc"
os = "windows"

    [[ERFA.download]]
    sha256 = "3906af666a2b0172461e5e98e5b29cf66f90ed20c1c5853cdc3f39671aac8460"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.2+0/ERFA.v1.7.2.x86_64-w64-mingw32.tar.gz"
