[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "49ac25172b1b5864b632a2c81eef54e32ee87291"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "eb18b911b678099147621857675e0aa26c6bfb3d4d0887de06ff9eed799b39a5"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.aarch64-linux-gnu.tar.gz"
[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "268f9c77a9e7493ce59d58fce0c7c3094af10862"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "6aed3ce4a40bf66c1fa368e30b3910435bcd04ef7b38851ab2eb410cdbc4d1c2"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.aarch64-linux-musl.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd6bfc53b65a9f992570eefc28f36f407eef1796"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "5427c2259983b4fa3d4c22e2d1d7f66fd5a55885938088a09c0465dc2336b563"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.armv7l-linux-gnueabihf.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d9733f46433371787af8f01c936a813cb5bf3ef"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "9aeccc110c7a17e410d295fa86690ce954bec840e4ee29e7948f647c1821986b"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.armv7l-linux-musleabihf.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "9e4d89a368fa89e2afde6c0d712310ebf7fb5f2c"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "81b9ea86a880a136b4cce94a25b7fc054303e48f501b2b335b45bc22daaecb9b"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.i686-linux-gnu.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "509c0f0505b8100d97533e126ec3a71b67397fbd"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "0bfb47808bf722cfd0161f9fde01cd22ab95e65de70c1be2ef7002eb535a3c29"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.i686-linux-musl.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "c9aa44ce11cbe8a3591c3ebe62c1b0cfd10ec506"
os = "windows"

    [[ERFA.download]]
    sha256 = "21822d29b7a950e631b902beb488fef3bc45f7ca59c1c6a460b2a56000e96fbb"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.i686-w64-mingw32.tar.gz"
[[ERFA]]
arch = "powerpc64le"
git-tree-sha1 = "4e59e4f40a73fc830a765ff94425b098900a0f27"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "681c53d935998f4a68f77f9b5f0133c9fa303c5002c0b4d477ffde58645af8f5"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.powerpc64le-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "860e816a6dbf2e61c6359f940b63d37a34c47c1d"
os = "macos"

    [[ERFA.download]]
    sha256 = "5aaef39531e6b5446849438eba846ed8a8d600a47fb5888f9064d8e85749101e"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.x86_64-apple-darwin.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "cb12174837ab5e458887d1d7f200bb698f9b55d1"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "62381f100918ce4212e2c13880f1338eb9ec7d7feb20c89126bb78168278d504"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.x86_64-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "5423c31ab8267df7b11cf9a166bbf4f71c1aa935"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "9e256e2f460bd56d48083f42cf3400d95921d58812aaf54fcf7ef5deda637110"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.x86_64-linux-musl.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "44938c963b749157356e0ee9b593fd04c85cfc11"
os = "freebsd"

    [[ERFA.download]]
    sha256 = "89b595a1ecf281b6a1f09880d22c83d012b2527561f7578ef318b4bb987304a4"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "64964f3cc6246251d5e38af2ab3b2ead498ff101"
os = "windows"

    [[ERFA.download]]
    sha256 = "a7bf91b4704a42bad274060004f2f4a350d9f6276ac41783bf35ba2179503a8c"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.1+0/ERFA.v1.7.1.x86_64-w64-mingw32.tar.gz"
