[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "7429eb9d8d7b698017076b753a33d85afec9bb4a"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "6db21a16f0e651e0d98ff38f05c1365b3e90a7253cbe612522c3b5aa922d9c03"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.aarch64-linux-gnu.tar.gz"
[[ERFA]]
arch = "aarch64"
git-tree-sha1 = "e250cf9b8e4082712572bb40b19bf528d6cc03e6"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "301968f0a8a74ca082efd1800573e0fdaaff3f8979247b5a92b6728e047044bb"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.aarch64-linux-musl.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "904ab4393f761fd9800d90b1373f62fe2c9c9516"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "508df476f7646c1791f29f301f519d5717dbe1793a097a9ba73cf446c939d8cf"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.armv7l-linux-gnueabihf.tar.gz"
[[ERFA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e71aa428e7a7ed2455dd86ab3410669a6549b17"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "48a062c65b110094cbb3580338d49f096ae1815cca64368b71ded02a9711bd2f"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.armv7l-linux-musleabihf.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "585e000b8ad3495de7fe7e87cf88c791800e883a"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "b46f68febcd528ffca88cddae7da8d9064942ace88ce292c5ee4a3f9cdec7f9b"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.i686-linux-gnu.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "bf333c49f136de5d9db48a2203d9a5e7e6d15e3c"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "ded2b56f5ebf17d6715617b933a706bbf3f349b684fe82af4b0df7fc583b9900"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.i686-linux-musl.tar.gz"
[[ERFA]]
arch = "i686"
git-tree-sha1 = "6665fc1baa1787a88cb5e1db2da18ddfc367c324"
os = "windows"

    [[ERFA.download]]
    sha256 = "b369ed5fb03be262c100b72a45baf6b0630daf60b6fff0a78bc5b40acc425aee"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.i686-w64-mingw32.tar.gz"
[[ERFA]]
arch = "powerpc64le"
git-tree-sha1 = "a8ecd2d6063bd4b4bf2d5228b589bbe7563b7e18"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "b4e240d563ab29259443388d362fb8e32d7b2bd360eb24fbdae9873e428932ac"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.powerpc64le-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "8309ca5fd4bd22e61a5adbd739d60d093db9eebf"
os = "macos"

    [[ERFA.download]]
    sha256 = "f533968339a8d3e61a631ec1666106f4a1b0632b6ea72c4c6c37c8804fb81f87"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.x86_64-apple-darwin.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "4a776abedb73710567347cda788f18e5ce66693c"
libc = "glibc"
os = "linux"

    [[ERFA.download]]
    sha256 = "2656968b99cc60c9d0c30ba6ea9140fa11780a3cd22db7df04f91e02348ea61d"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.x86_64-linux-gnu.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "fb718ab3b51b05f9da85312533ccb934c22023af"
libc = "musl"
os = "linux"

    [[ERFA.download]]
    sha256 = "c27eb6f7d235665f0069b6f88e6b35b4ec1cb8304e0cb6c5728af08df5cecb9a"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.x86_64-linux-musl.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "b64bce2983d86364adc65729ae90ab9d63de1056"
os = "freebsd"

    [[ERFA.download]]
    sha256 = "51c0410d769e9328fd8b871f9015599d6ec59660da01f03d1f2cc10e437b0087"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.x86_64-unknown-freebsd.tar.gz"
[[ERFA]]
arch = "x86_64"
git-tree-sha1 = "5705d2ba4cd210c5c9ae9200f6cf709587650895"
os = "windows"

    [[ERFA.download]]
    sha256 = "9ce28d527fe8cbf3618ed2dae1d1b2189d303b76594799674cc33096f1f4ef45"
    url = "https://github.com/JuliaBinaryWrappers/ERFA_jll.jl/releases/download/ERFA-v1.7.3+0/ERFA.v1.7.3.x86_64-w64-mingw32.tar.gz"
